# Generated by Django 3.2.8 on 2021-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
    ]
